--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyShopUI
branches:
  - master
projects:
  PiggyShopUI:
    path: ""
    libs:
      - src: ACM-PocketMine-MP/FormsUI/FormsUI
        version: ^1.1.4
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
        branch: PM5
      - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
        version: ^3.0.3
      - src: ACM-PocketMine-MP/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^2.0.0
    lint:
      phpstan: false
...
