--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyShopUI
branches:
- master
- 2.0.0
projects:
  PiggyShopUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    - src: CortexPE/Commando/Commando
      version: ^0.5
...
